### ISSUE TITLE
自定义config headers丢失

### ISSUE THREAD

**Issue by changweihua** [zjx0905/axios-miniprogram#43]
### 描述错误

2.3.1 中，自定义config headers丢失

### 附加上下文

没看懂为啥要delete config header
![微信截图_20230423131318](https://user-images.githubusercontent.com/2877201/233821079-2643afb2-13f0-41ed-a55e-004fd11b9e36.png)

### 使用过的包管理器

npm

### 验证

- [X] 遵守我们的[行为准则 ](https://github.com/zjx0905/axios-miniprogram/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读[贡献指南](https://github.com/zjx0905/axios-miniprogram/blob/main/CONTRIBUTING.md).
- [X] 阅读[文档](https://axios-miniprogram.com).
- [X] 检查是否还没有报告相同错误的[问题](https://github.com/zjx0905/axios-miniprogram/issues)以避免创建重复。
- [X] 确保这是 axios-miniprogram 问题而不是特定于框架的问题。

**Comment by zjx0905** [comment]
`common` 字段已经被默认配置占用了，这里的实现和 `axios` 是一致的。

全局设置可以

```ts
axios.defaults.headers.common['common'] = '你的属性';

// 或者给方法设置

axios.defaults.headers.get['common'] = '你的属性';
axios.defaults.headers.post['common'] = '你的属性';
```

局部设置可以

```ts
axios.get(
  'url',
  {},
  {
    headers: {
      get: {
        common: '你的属性',
      },
    },
  },
);

axios.post(
  'url',
  {},
  {
    headers: {
      post: {
        common: '你的属性',
      },
    },
  },
);
```

建议在条件允许的情况下，优先考虑换个其他的名称。

**Comment by changweihua** [comment]
![微信图片_20230423135628](https://user-images.githubusercontent.com/2877201/233822424-72a14b43-0e40-44c4-9f46-76991ab8c4d3.png)

我在拦截器中，增加header值，2.3.0中 request header 中是包含这些值的，但是在2.3.1中，request header 里面没有这些值，我看了下代码，感觉这里有点奇怪。没明白为啥要delete config.headers。

感谢。

**Comment by zjx0905** [comment]
意思是说红框中的设置在 2.3.1 中丢失了吗？

**Comment by changweihua** [comment]
是的

**Comment by zjx0905** [comment]
2.3.2 已经修复

**Comment by changweihua** [comment]
已测试，OK了，感谢。
