### ISSUE TITLE
必须设置 axios.interceptors.request.use 才可以请求，不然会显示配置不正确或者网络异常

### ISSUE THREAD

**Issue by 1014156094** [zjx0905/axios-miniprogram#5]
没设置 axios.interceptors.request.use 会显示配置不正确或者网络异常
![image](https://user-images.githubusercontent.com/16074662/89480831-f0b44b00-d7c8-11ea-978d-b494b731625b.png)
![image](https://user-images.githubusercontent.com/16074662/89480893-1ccfcc00-d7c9-11ea-862f-7014a17e116d.png)

设置之后则可以正常请求
![image](https://user-images.githubusercontent.com/16074662/89481039-733d0a80-d7c9-11ea-8d90-750102a44f01.png)
![image](https://user-images.githubusercontent.com/16074662/89481052-79cb8200-d7c9-11ea-8f47-900adcf85f9a.png)

**Comment by 1014156094** [comment]
> ![image](https://user-images.githubusercontent.com/16074662/89480831-f0b44b00-d7c8-11ea-978d-b494b731625b.png)
> ![image](https://user-images.githubusercontent.com/16074662/89480893-1ccfcc00-d7c9-11ea-862f-7014a17e116d.png)
设置之后则可以正常请求
![image](https://user-images.githubusercontent.com/16074662/89480962-4557c600-d7c9-11ea-8c99-680a6bcb1ffa.png)
![image](https://user-images.githubusercontent.com/16074662/89480996-56083c00-d7c9-11ea-8920-d7d8f2007d4a.png)

**Comment by zjx0905** [comment]
您好，请问使用 axios.interceptors.request.use 前，您是否有设置过 axios.defaults.baseURL

**Comment by zjx0905** [comment]
> 没设置axios.interceptors.request.use会显示配置不正确或者网络异常
> ![图片](https://user-images.githubusercontent.com/16074662/89480831-f0b44b00-d7c8-11ea-978d-b494b731625b.png)
> ![图片](https://user-images.githubusercontent.com/16074662/89480893-1ccfcc00-d7c9-11ea-862f-7014a17e116d.png)
> 
> 设置之后则可以正常请求
> ![图片](https://user-images.githubusercontent.com/16074662/89481039-733d0a80-d7c9-11ea-8d90-750102a44f01.png)
> ![图片](https://user-images.githubusercontent.com/16074662/89481052-79cb8200-d7c9-11ea-8f47-900adcf85f9a.png)

您好，请问使用 axios.interceptors.request.use 前，您是否有设置过 axios.defaults.baseURL。

**Comment by 1014156094** [comment]
> baseURL

设置了 baseURL 才能使用

**Comment by zjx0905** [comment]
> > baseURL
> 
> 设置了baseURL才能使用

**Comment by zjx0905** [comment]
> > baseURL
> 
> 设置了baseURL才能使用

URL正确应该就不会报异常

**Comment by zjx0905** [comment]
没有设置 baseURL 前，应该请求完整的地址，例 axios('www.zheshidizhi.com/api')。
设置过 axios.defauls.baseURL = 'www.zheshidizhi.com' 后，可以这样简写 axios('/api')。
