### ISSUE TITLE
实例如何继承全局拦截器

### ISSUE THREAD

**Issue by zcjunblog** [zjx0905/axios-miniprogram#7]
我查看了原版axios的仓库明白了这是一个功能，而不是错误。
但还是想问一下如何在axios-miniprogram里让实例继承全局拦截器?
盼回复...

**Comment by zjx0905** [comment]
您好，`axios` 和自定义实例都是 `Axios` 的实例，而拦截器是在 `Axios` 实例化的过程中初始化的，所以无法实现继承，只能再次一一注册。[https://github.com/axios/axios/blob/ffea03453f77a8176c51554d5f6c3c6829294649/lib/core/Axios.js#L16](axios)

**Comment by zcjunblog** [comment]
> https://github.com/axios/axios/blob/ffea03453f77a8176c51554d5f6c3c6829294649/lib/core/Axios.js#L16

好的 明白了  谢谢
